'use client'

// import type { Metadata } from "next";
import { Vazirmatn } from 'next/font/google'
import "./globals.css";
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";

import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

// If loading a variable font, you don't need to specify the font weight
const vazir = Vazirmatn({
    subsets: ['latin'],
    display: 'swap',
  })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${vazir.className}`}
      >
        <Header />
        <main>
            {children}
            <ToastContainer />
        </main>
        <Footer />
      </body>
    </html>
  );
}
